# server配置
server:
  port: 8080
  servlet:
    context-path: /

# 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///sm_headline
      username: root
      password: '20181413'
      driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.hhx.pojo
  global-config:
    db-config:
      logic-delete-field: isDelete #全局逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto # 主键策略自增长
      table-prefix: news_ # 设置表的前缀


#jwt配置
jwt:
  token:
    tokenExpiration: 120 #有效时间，单位分钟
    tokenSignKey: headline123456 #当前程序签名密钥 自定义